### ISSUE TITLE
Kick Off

### ISSUE THREAD

**Issue by jamesnyakush** [jamesnyakush/Employer-Self-Service#4]
We need to decided the following before we continue

1. Design Pattern. 
2. DI Library.

**Comment by jumaallan** [comment]
DI - Use KOIN

**Comment by GypsyTheDj** [comment]
dependencies {
    // Koin for Kotlin apps
    compile 'org.koin:koin-core:2.0'
    // Testing
    testCompile 'org.koin:koin-test:2.0'
}

**Comment by jamesnyakush** [comment]
This is great was just thinking about database what should we use a backend or firebase  or our own backend
